### ISSUE TITLE
java.lang.IllegalStateException: Attempt to reinitialise the CacheManager

### ISSUE THREAD

**Issue by andrebrov** [grails-plugins/grails-cache-ehcache#26]
I'm using version 2.0.0.BUILD-SNAPSHOT with org.grails.plugins:cache:3.0.1 and I'm getting

```
java.lang.IllegalStateException: Attempt to reinitialise the CacheManager
    at net.sf.ehcache.CacheManager.reinitialisationCheck(CacheManager.java:778)
    at net.sf.ehcache.CacheManager.parseConfiguration(CacheManager.java:673)
    at net.sf.ehcache.CacheManager.init(CacheManager.java:369)
    at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager.rebuild(GrailsEhCacheManagerFactoryBean.java:179)
    at grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager$rebuild.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at grails.plugin.cache.ehcache.EhcacheConfigLoader.reload(EhcacheConfigLoader.groovy:63)
    at grails.plugin.cache.ehcache.EhcacheConfigLoader$reload.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
    at grails.plugin.cache.ConfigLoader.reload(ConfigLoader.groovy:42)
    at grails.plugin.cache.ConfigLoader$reload.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at grails.plugin.cache.CacheGrailsPlugin.reloadCaches(CacheGrailsPlugin.groovy:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    at grails.plugin.cache.CacheGrailsPlugin.doWithApplicationContext(CacheGrailsPlugin.groovy:137)
    at org.grails.plugins.DefaultGrailsPlugin.doWithApplicationContext(DefaultGrailsPlugin.java:523)
    at org.grails.plugins.AbstractGrailsPluginManager.doPostProcessing(AbstractGrailsPluginManager.java:229)
    at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy:231)
    at grails.boot.config.GrailsApplicationPostProcessor.onApplicationEvent(GrailsApplicationPostProcessor.groovy)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:331)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:775)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:139)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:117)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:689)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:51)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:335)
    at grails.boot.GrailsApp.run(GrailsApp.groovy:324)
    at grails.boot.GrailsApp$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
    at scentbird.admin.Application.main(Application.groovy:10)
```

Very similar to http://stackoverflow.com/questions/36677195/possible-issue-with-ehcache-plugin-on-grails-3

**Comment by rvachtl** [comment]
Try following in the build.gradle:

    compile ("org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT") {
      exclude group:'net.sf.ehcache'
    }
    compile "net.sf.ehcache:ehcache:2.4.3"

**Comment by PiotrZakrzewski** [comment]
This fixes this issue for me - thanks @rvachtl !

**Comment by rlovtangen** [comment]
It seems to work in Grails 3.2.3 when downgrading ehcache to 2.4.3, which was the version used by org.hibernate:hibernate-ehcache (4.3.11.Final) in Grails 3.1.11.
But Grails 3.2.3 use org.hibernate:hibernate-ehcache:5.1.2.Final, which depend on net.sf.ehcache:ehcache:2.10.1. So it doesn't feel safe to downgrade ehcache all the way down to 2.4.3

I noticed [this](https://github.com/grails-plugins/grails-cache-ehcache/commit/a1a99bd182e3e1cb2c351fd96d3872d273f26dcb#commitcomment-15938862) comment, which seems related. The commit comment says "This code is currently problematic at startup.  Pending investigation"

**Comment by rlovtangen** [comment]
Btw: tested with ehcache 2.4.8, which also works. Starts failing from 2.5.0

**Comment by purpleraven** [comment]
Can't fix the error by downgrading of ehcache

> 04/12 15:22:45.363 WARN net.sf.ehcache.CacheManager - Creating a new instance of CacheManager using the diskStorePath "/var/folders/5_/g9k_282j75d8tyypfryqmptw0000gn/T/" which is already used by an existing CacheManager.
> The source of the configuration was net.sf.ehcache.config.generator.ConfigurationSource$InputStreamConfigurationSource@361a1e86.
> The diskStore path for this CacheManager will be set to /var/folders/5_/g9k_282j75d8tyypfryqmptw0000gn/T//ehcache_auto_created_1480861365363.
> To avoid this warning consider using the CacheManager factory methods to create a singleton CacheManager or specifying a separate ehcache configuration (ehcache.xml) for each CacheManager instance.
> 04/12 15:22:45.364 WARN net.sf.ehcache.Cache - Cache: grailsTemplatesCache has a maxElementsInMemory of 0.  In Ehcache 2.0 this has been changed to mean a store with no capacity limit. Set it to 1 if you want no elements cached in memory
> 04/12 15:22:45.370 WARN net.sf.ehcache.Cache - Cache: grailsBlocksCache has a maxElementsInMemory of 0.  In Ehcache 2.0 this has been changed to mean a store with no capacity limit. Set it to 1 if you want no elements cached in memory
> 04/12 15:22:45.820 INFO org.grails.spring.GrailsApplicationContext - Refreshing org.grails.spring.GrailsApplicationContext@1d0b4b69: startup date [Sun Dec 04 15:22:45 CET 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@69aa7d76
> Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
> 04/12 15:22:51.639 ERROR org.springframework.boot.SpringApplication - Application startup failed
> java.lang.IllegalStateException: Attempt to reinitialise the CacheManager
>         at net.sf.ehcache.CacheManager.reinitialisationCheck(CacheManager.java:676)
>         at net.sf.ehcache.CacheManager.parseConfiguration(CacheManager.java:542)
>         at net.sf.ehcache.CacheManager.init(CacheManager.java:309)

Grails 3.2.3
```
    compile ("org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT") {
        exclude group:'net.sf.ehcache'
    }
    compile "net.sf.ehcache:ehcache:2.4.3"
    compile "org.grails.plugins:hibernate4"
    compile "org.hibernate:hibernate-core:4.3.11.Final"
    compile "org.hibernate:hibernate-ehcache:4.3.11.Final"
```

> +--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
> |    \--- org.grails.plugins:cache:4.0.0.BUILD-SNAPSHOT -> 3.0.3
> |         +--- com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
> |         \--- org.javassist:javassist:3.17.1-GA -> 3.20.0-GA
> ......
> +--- net.sf.ehcache:ehcache:2.4.3
> |    +--- net.sf.ehcache:ehcache-core:2.4.3
> |    |    \--- org.slf4j:slf4j-api:1.6.1 -> 1.7.21
> |    \--- net.sf.ehcache:ehcache-terracotta:2.4.3
> .......
> +--- org.hibernate:hibernate-ehcache:4.3.11.Final
> |    +--- org.jboss.logging:jboss-logging:3.1.3.GA -> 3.3.0.Final
> |    +--- org.jboss.logging:jboss-logging-annotations:1.2.0.Beta1
> |    +--- org.hibernate:hibernate-core:4.3.11.Final (*)
> |    \--- net.sf.ehcache:ehcache-core:2.4.3 (*)
> .......
> +--- org.grails.plugins:spring-security-core:3.1.1
> |    +--- net.sf.ehcache:ehcache:2.9.0 -> 2.4.3 (*)

**Comment by jameskleeh** [comment]
Due to changes in design, the issue won't occur in 3.0.0
