### ISSUE TITLE
latest change has broke the plugin on 3.10

### ISSUE THREAD

**Issue by vahidhedayati** [grails-plugins/grails-cache-ehcache#32]
I can see the plugin has been updated yesterday and as of yesterday I can no longer load app up locally or in tomcat with the ehcache-plugin

build line: (the commented lines was previous hack)
```groovy
compile ("org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT") {
       // exclude group:'net.sf.ehcache'
    }
    //compile "net.sf.ehcache:ehcache:2.4.3"
```
But since this release is also `3.0.0.BUILD-SNAPSHOT` means  all versions of my code is broke. Meaning I rolled back thinking what has changed.

Comparing the results of jar files produced. This is a new file that did not exist in older produced jar files:

```
ehcache-3.3.1.jar
```

Any advice on how to fix would be appreciated

```Error : 

```
ERROR org.springframework.boot.context.embedded.tomcat.TomcatStarter - Error starting Tomcat context: org.springframework.beans.factory.BeanCreationException
ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:365)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:354)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at myprofessions.Application.main(Application.groovy:77)
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:99)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:76)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:457)
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:168)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsCacheFilter': Cannot create inner bean '(inner bean)#ba990c0' of type [grails.plugin.cache.web.filter.simple.MemoryPageFragmentCachingFilter] while setting bean property 'filter'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#ba990c0': Cannot resolve reference to bean 'grailsCacheManager' while setting bean property 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsCacheManager': Cannot resolve reference to bean 'ehcacheConfiguration' while setting bean property 'configuration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ehcacheConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:129)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:233)
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:214)
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:90)
	at org.springframework.boot.context.embedded.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:78)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getServletContextInitializerBeans(EmbeddedWebApplicationContext.java:237)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:224)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:209)
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#ba990c0': Cannot resolve reference to bean 'grailsCacheManager' while setting bean property 'cacheManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsCacheManager': Cannot resolve reference to bean 'ehcacheConfiguration' while setting bean property 'configuration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ehcacheConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
	... 26 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsCacheManager': Cannot resolve reference to bean 'ehcacheConfiguration' while setting bean property 'configuration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ehcacheConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 32 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ehcacheConfiguration': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 42 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 51 common frames omitted
Caused by: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/user/project/build/resources/main/ehcache.xml
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:167)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:131)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:115)
	at grails.plugin.cache.ehcache.DefaultXmlConfiguration.<init>(DefaultXmlConfiguration.groovy:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 53 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-elt.1.a: Cannot find the declaration of element 'ehcache'.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177)
	at org.ehcache.xml.ConfigurationParser.<init>(ConfigurationParser.java:159)
	at org.ehcache.xml.XmlConfiguration.parseConfiguration(XmlConfiguration.java:175)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:163)
	... 62 common frames omitted

```

**Comment by jameskleeh** [comment]
The plugin was updated to use ehcache 3. It looks like the XML you are supplying is not compatible with ehcache 3.

**Comment by vahidhedayati** [comment]
Still getting the same error:
My ehcache.xml:
I have also included the xsd into same folder  from http://www.ehcache.org/ehcache.xsd (as of yesterday, after hitting the issue) 

I have referred to the https://grails-plugins.github.io/grails-cache-ehcache/guide/usage.html page and put in a default. 

```

<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ehcache.xsd">
<diskStore path="java.io.tmpdir" />

<defaultCache
maxElementsInMemory="10000"
eternal="false"
timeToIdleSeconds="120"
timeToLiveSeconds="120"
overflowToDisk="true"
maxElementsOnDisk="10000000"
diskPersistent="false"
diskExpiryThreadIntervalSeconds="120"
memoryStoreEvictionPolicy="LRU"
/>
</ehcache>

```
When attempting to start  locally: This is with the hacks commented out 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.plugin.cache.ehcache.DefaultXmlConfiguration]: Constructor threw exception; nested exception is org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/.../ehcache.xml
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
	... 51 common frames omitted
Caused by: org.ehcache.xml.exceptions.XmlConfigurationException: Error parsing XML configuration at file:/home/.../ehcache.xml
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:167)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:131)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:115)
	at grails.plugin.cache.ehcache.DefaultXmlConfiguration.<init>(DefaultXmlConfiguration.groovy:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1075)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 53 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-elt.1.a: Cannot find the declaration of element 'ehcache'.
```

**Comment by jameskleeh** [comment]
The xsd is not relevant. The plugin documentation has not been updated. Refer to the ehcache documentation on how to build your xml document

http://www.ehcache.org/documentation/3.0/xml.html

**Comment by vahidhedayati** [comment]
Still think there is an issue here.

Upgraded to latest version of grails as a test in dependency report


+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3


Issue hit 

http://forums.terracotta.org/forums/posts/list/3748.page

Full list of dependencies:

$ grails dependency-report|grep ehcache
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
\--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
     \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
\--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
     \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4
+--- org.hibernate:hibernate-ehcache:5.1.3.Final
|    \--- net.sf.ehcache:ehcache:2.10.1 -> 2.10.3
+--- org.grails.plugins:cache-ehcache:3.0.0.BUILD-SNAPSHOT
|    \--- org.ehcache:ehcache:3.3.1 -> 3.1.4



Trying to start the app with a default config of v3 generates this error:
$ cat grails-app/conf/ehcache.xml
```
<eh:config
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:eh='http://www.ehcache.org/v3'
    xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
    xsi:schemaLocation="
        http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
        http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd">
</eh:config>
```
```
Initial cause was Error configuring from input stream. Initial caus                                                                                                                                                                                               e was null:7: Element <eh:config> does not allow attribute "xmlns:xsi".
        at org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory.start(Singl                                                                                                                                                                                               etonEhCacheRegionFactory.java:90)
        at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:49)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiato                                                                                                                                                                                               r.java:28)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiato                                                                                                                                                                                               r.java:20)
```

Referring to this post http://forums.terracotta.org/forums/posts/list/3748.page

and having disabled 
//compile ("org.hibernate:hibernate-ehcache:5.1.3.Final")  {
     //  exclude group:'net.sf.ehcache'
    //}

and in application.yml removing hibernate segment

```
---
...removed
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:
```

Application starts up fine.


Either way this doesn't resolve older grails 3.1x apps that run on slightly older hibernate and the new updates will break them unless they all upgrade to the latest grails that then has a fix for this bit

**Comment by jameskleeh** [comment]
So the issue is that the ehcache hibernate is including is picking up your configuration. My advice would be to rename it to something else and configure the plugin to its new location. 

`grails.cache.ehcache.ehcacheXmlLocation: classpath:ehcache-3.xml`
