### ISSUE TITLE
"3.0.0.BUILD-SNAPSHOT" - java.lang.NoClassDefFoundError: org/grails/plugin/cache/GrailsCacheManager

### ISSUE THREAD

**Issue by aaporjr** [grails-plugins/grails-cache-ehcache#33]
to reproduce:

- create new grails 3.2.4 app
- configure deps accordingly
- run app

**actual behavior**
- NoClassDefFoundError thrown
`CONFIGURE SUCCESSFUL

Total time: 7.512 secs
| Running application...
Listening for transport dt_socket at address: 56856
Connected to the target VM, address: '127.0.0.1:56856', transport: 'socket'
2017-04-20 21:28:47.827 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed
Disconnected from the target VM, address: '127.0.0.1:56856', transport: 'socket'

java.lang.NoClassDefFoundError: org/grails/plugin/cache/GrailsCacheManager
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at cacheehcache.CacheEhcacheGrailsPlugin$_doWithSpring_closure1.doCall(CacheEhcacheGrailsPlugin.groovy:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
        at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
        at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
        at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
        at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:167)
        at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:387)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
        at grails.boot.GrailsApp$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at myapp.Application.main(Application.groovy:8)
Caused by: java.lang.ClassNotFoundException: org.grails.plugin.cache.GrailsCacheManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 45 common frames omitted`

**expected behavior**
- app should run properly

**example app**
[https://github.com/aaporjr/grails-cache-ehcache-NoClassDefFoundError](https://github.com/aaporjr/grails-cache-ehcache-NoClassDefFoundError)

**Comment by jameskleeh** [comment]
The plugin relies on cache 4.0.0 or higher.

`compile "org.grails.plugins:cache:4.0.0.BUILD-SNAPSHOT"`

You will also need to upgrade to GORM 6.1

**Comment by aaporjr** [comment]
thanks @jameskleeh, i'll try that

**Comment by vahidhedayati** [comment]
Trying to upgrade to gorm6.1  from https://github.com/grails-plugins/grails-cache-ehcache/issues/33 and attempting this https://github.com/grails/grails-core/issues/10567 I get : Execution failed for task ':compileGroovy'.
> org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.buildDelegatingMethodCall(Lorg/codehaus/groovy/control/SourceUnit;Lorg/codehaus/groovy/ast/AnnotationNode;Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/MethodNode;Lorg/codehaus/groovy/ast/expr/MethodCallExpression;Lorg/codehaus/groovy/ast/stmt/BlockStatement;)Lorg/codehaus/groovy/ast/expr/MethodCallExpression;

[5:39] 
Anyone have any ideas how to resolve this ?

[5:41] 
compile "org.grails.plugins:cache:4.0.0.BUILD-SNAPSHOT"  When I disable this it goes away

It appears adding:
```
compile "org.grails.plugins:cache:4.0.0.BUILD-SNAPSHOT"
```
causes described scenario

**Comment by jameskleeh** [comment]
@vahidhedayati Create a new issue in the cache plugin issue tracker with an example project and I'll look at it
